services:
  api:
    container_name: api
    build:
      context: ./server
      dockerfile: ./Dockerfile
    environment:
      - PORT=4000
    ports:
      - 4000:4000
  web:
    container_name: web
    build:
      context: ./client
      dockerfile: ./Dockerfile
    depends_on:
      - api
    ports:
      - 3000:3000
    links:
      - api