services:
  api:
    container_name: api
    build:
      context: ./server
      dockerfile: ./Dockerfile
    restart: always
    environment:
      - PORT=4000
    ports:
      - 4000:4000
  web:
    container_name: web
    build:
      context: ./client
      dockerfile: ./Dockerfile
    restart: always
    environment:
      - NEXT_PUBLIC_GRAPHQL_SERVER=http://localhost:4000/graphql
    ports:
      - 3000:3000
    links:
      - api